# Generated by Django 5.2.1 on 2025-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='status',
            field=models.CharField(default='Processando', max_length=20),
        ),
    ]
